name: Outscale API release
on:
  release:
    types: [released]

jobs:
  osc-api-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Getting release details
        id: release
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: Trigger osc-api-deploy build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_OSC_API_DEPLOY }}
          API_VERSION: ${{ steps.release.outputs.TAG }}
        run: .github/scripts/build-osc-sdk.sh osc-api-deploy main
